In [21]:
import numpy as np

arr = np.array([[1, 7, 3], [8, 2, 9], [4, 5, 6]])

print("Original Array:")
print(arr)
print("arr.shape:", arr.shape)

print("\n== Accessing Elements ==")

print("Element at row 1, column 2:", arr[1, 2])  # Accessing the element at row 1, column 2
print("First row:", arr[0, :])  # Accessing the first row
print("Second column:", arr[:, 1])  # Accessing the second column

print("\n== Sorting: ==")

print("Sorted Array for rows:")
arr.sort(axis=1)  
print(arr)

print("Sorted Array for columns:")
arr.sort(axis=0)  # Sort along the first axis (rows)
print(arr)

Original Array:
[[1 7 3]
 [8 2 9]
 [4 5 6]]
arr.shape: (3, 3)

== Accessing Elements ==
Element at row 1, column 2: 9
First row: [1 7 3]
Second column: [7 2 5]

== Sorting: ==
Sorted Array for rows:
[[1 3 7]
 [2 8 9]
 [4 5 6]]
Sorted Array for columns:
[[1 3 6]
 [2 5 7]
 [4 8 9]]
